### ISSUE TITLE
Broken links to ceda.ac.uk/contact/

### ISSUE THREAD

**Issue by gap736uk** [cedadev/ceda-div-hugo-hinode#50]
We have various services which will have linked to the ceda.ac.uk/contact/ page.

This page used to have our contact info including our postal address, Twitter feed etc.

options:
1. reinstate such a contact page
2. update the links and have these toggle the beacon contact page to open where we find such linking (can we find all these places somehow?)

**Comment by danny-lloyd** [comment]
Fixed by https://github.com/cedadev/ceda-div-hugo-hinode/commit/5851f3e72d55e5b9de297a27c5338bad96600647
